define(['knockout','ojs/ojarraydataprovider','services/api','viewModels/base','ojs/ojtable'], function (ko, ArrayDataProvider, api, BaseViewModel) {
  'use strict';
  function AlertsViewModel(params){
    var self=this; BaseViewModel.call(self); self.severity=ko.observable('All severities'); self.status=ko.observable('All statuses');
    self.rows=ko.observableArray([]); self.error=ko.observable(''); self.loading=ko.observable(true); self.busy=ko.observable(false);
    self.search=params&&params.globalSearch||ko.observable('');
    self.filtered=ko.computed(function(){var q=String(self.search()||'').toLowerCase();return self.rows().filter(function(a){return (self.severity()==='All severities'||a.severity===self.severity())&&(self.status()==='All statuses'||a.status===self.status())&&(!q||[a.id,a.customer,a.txn,a.type,a.severity,a.status,a.analyst].join(' ').toLowerCase().indexOf(q)>=0);});});
    self.dataProvider=ko.pureComputed(function(){return new ArrayDataProvider(self.filtered(),{keyAttributes:'id'});}); self.selectedAlert=ko.observable(null); self.selectedCustomer=ko.observable(null);
    self.openAlert=function(alert){self.selectedAlert(alert||null);}; self.closeAlert=function(){self.selectedAlert(null);};
    function createCase(owner){var alert=self.selectedAlert();if(!alert)return Promise.resolve();self.busy(true);self.error('');return api.post('/cases',{transactionId:alert.txn,owner:owner||null,priority:alert.severity}).then(function(item){alert.status='ESCALATED';alert.analyst=item.owner||'Unassigned';alert.caseId=item.id;self.rows.valueHasMutated();return item;}).catch(function(e){self.error(e.message);throw e;}).finally(function(){self.busy(false);});}
    self.markFalsePositive=function(){var alert=self.selectedAlert();if(!alert)return;self.busy(true);api.put('/transactions/business/'+encodeURIComponent(alert.txn)+'/review',{status:'COMPLETED'}).then(function(){alert.status='RESOLVED';self.rows.valueHasMutated();self.closeAlert();}).catch(function(e){self.error(e.message);}).finally(function(){self.busy(false);});};
    self.assignAnalyst=function(){createCase('J. Doshi').catch(function(){});}; self.createInvestigation=function(){createCase(null).then(function(){self.closeAlert();}).catch(function(){});};
    Promise.all([api.get('/transactions'),api.get('/cases')]).then(function(results){var cases=results[1]||[];return Promise.all((results[0]||[]).map(function(t){return api.get('/transactions/'+encodeURIComponent(t.transactionId)+'/risk').then(function(r){if(!r.shouldFlag)return null;var item=cases.find(function(c){return c.transactionId===t.transactionId;});return{id:r.requestId||t.id,customer:t.senderAccountId,txn:t.transactionId,type:r.oneLineExplanation||r.riskCategory||'AML risk model flag',severity:String(r.riskCategory||'HIGH').toUpperCase(),score:Math.round(Number(r.riskScore||0)),status:item?item.status:'NEW',analyst:item&&item.owner||'Unassigned',created:r.createdAt?new Date(r.createdAt).toLocaleString():'',caseId:item&&item.id};}).catch(function(){return null;});}));}).then(function(items){self.rows(items.filter(Boolean));}).catch(function(e){self.error(e.message);}).finally(function(){self.loading(false);});
  } return AlertsViewModel;
});
