define(['knockout','ojs/ojarraydataprovider','services/api','viewModels/base','ojs/ojtable'], function(ko,ArrayDataProvider,api,BaseViewModel){
  'use strict';
  function InvestigationsViewModel(){var self=this;BaseViewModel.call(self);self.rows=ko.observableArray([]);self.error=ko.observable('');self.loading=ko.observable(true);self.dataProvider=ko.pureComputed(function(){return new ArrayDataProvider(self.rows(),{keyAttributes:'id'});});self.selectedInvestigation=ko.observable(null);self.noteDraft=ko.observable('');self.timeline=ko.observableArray([]);self.selectedCustomer=ko.observable(null);
    function map(i){return{id:i.id,alert:i.transactionId,customer:i.customerId,owner:i.owner||'Unassigned',priority:i.priority,status:i.status,created:i.createdAt?new Date(i.createdAt).toLocaleDateString():'',due:'—',resolution:i.resolution||'—'};}
    api.get('/cases').then(function(items){self.rows((items||[]).map(map));}).catch(function(e){self.error(e.message);}).finally(function(){self.loading(false);});
    self.priorityClass=function(v){return String(v||'').toLowerCase();};self.statusClass=function(v){return String(v||'').toLowerCase().replace(/\s+/g,'-').replace(/_/g,'-');};self.openInvestigation=function(i){self.selectedInvestigation(i||null);self.timeline([{title:'Investigation opened',detail:'Backend case '+i.id}]);};self.closeInvestigation=function(){self.selectedInvestigation(null);};self.addNote=function(){var n=self.noteDraft().trim();if(n){self.timeline.push({title:'Analyst note (session only)',detail:n});self.noteDraft('');}};
    function update(change,title){var item=self.selectedInvestigation();if(!item)return;api.put('/cases/'+encodeURIComponent(item.id),change).then(function(saved){Object.assign(item,map(saved));self.rows.valueHasMutated();self.timeline.push({title:title,detail:'Saved to investigation service'});}).catch(function(e){self.error(e.message);});}
    self.escalate=function(){update({status:'ESCALATED'},'Case escalated');};self.resolve=function(){update({status:'RESOLVED',resolution:'Resolved by analyst'},'Case resolved');};self.create=function(){self.error('Create a case from a flagged transaction in AML alerts.');};
  } return InvestigationsViewModel;
});
