define(['ojs/ojarraydataprovider','models/data','viewModels/base','ojs/ojtable'], function(ArrayDataProvider,data,BaseViewModel){
  'use strict';
  function ReportsViewModel(){var self=this;BaseViewModel.call(self);self.rows=data.investigations.map(function(i,n){return{id:'RPT-'+(3100+n),type:n%2?'INVESTIGATION REPORT':'SUSPICIOUS TRANSACTION REPORT',reference:i.id,owner:i.owner,date:i.created,status:'READY'};});self.dataProvider=new ArrayDataProvider(self.rows,{keyAttributes:'id'});self.columns=[{headerText:'REPORT',field:'id'},{headerText:'TYPE',field:'type'},{headerText:'REFERENCE',field:'reference'},{headerText:'GENERATED BY',field:'owner'},{headerText:'DATE',field:'date'},{headerText:'STATUS',field:'status'}];self.generate=function(){window.alert('Report generation started.');};self.download=function(){window.alert('Secure report download started.');};}
  return ReportsViewModel;
});
