define(['knockout','ojs/ojarraydataprovider','services/api','viewModels/base','ojs/ojtable'], function(ko,ArrayDataProvider,api,BaseViewModel){
  'use strict';
  function TransactionsViewModel(params){
    var self=this;BaseViewModel.call(self);self.rows=ko.observableArray([]);self.error=ko.observable('');self.loading=ko.observable(true);self.search=params&&params.globalSearch||ko.observable('');self.selectedTransaction=ko.observable(null);
    self.filtered=ko.computed(function(){var q=String(self.search()||'').toLowerCase();return self.rows().filter(function(t){return !q||[t.transactionId,t.senderAccountId,t.receiverAccountId,t.paymentType,t.status,t.riskCategory].join(' ').toLowerCase().indexOf(q)>=0;});});
    self.dataProvider=ko.pureComputed(function(){return new ArrayDataProvider(self.filtered(),{keyAttributes:'id'});});self.openTransaction=function(t){self.selectedTransaction(t||null);};self.closeTransaction=function(){self.selectedTransaction(null);};
    Promise.all([api.get('/transactions'),api.get('/cases')]).then(function(results){var cases=results[1]||[];return Promise.all((results[0]||[]).map(function(t){return api.get('/transactions/'+encodeURIComponent(t.transactionId)+'/risk').catch(function(){return null;}).then(function(r){t.displayDate=t.transactionDatetime?new Date(t.transactionDatetime).toLocaleString():'—';t.displayAmount=new Intl.NumberFormat('en-US',{style:'currency',currency:t.paymentCurrency||'USD'}).format(Number(t.amount||0));t.riskScore=r?Math.round(Number(r.riskScore||0)):0;t.riskCategory=String(r&&r.riskCategory||'LOW').toUpperCase();t.flagged=!!(r&&r.shouldFlag);t.explanation=r&&r.oneLineExplanation||'No unusual behavior detected.';t.recommendation=r&&r.recommendation||'Continue routine monitoring.';t.caseRecord=cases.find(function(c){return c.transactionId===t.transactionId;});return t;});}));}).then(function(items){self.rows(items);}).catch(function(e){self.error(e.message);}).finally(function(){self.loading(false);});
  } return TransactionsViewModel;
});
